version: '3'
services:
  db:
    image: postgres
    volumes:
    - db-data:/var/lib/postgresql/data
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    expose:
    - "8000"
    volumes:
    - .:/code
    depends_on:
    - db
    - centrifugo
  centrifugo:
    image: centrifugo/centrifugo
    command: centrifugo -c centrifugo.json
    volumes:
    - ./config:/centrifugo
    expose:
    - "8020"
  nginx:
    image: nginx
    ports:
    - "80:80"
    expose: ["80"]
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
    - centrifugo
    - django
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./static:/usr/share/nginx/html
volumes:
  db-data: